data:
  data_path: "/Users/mrartemev/Datasets/HEP/RICH2021"
  val_size: 0.1
  download: False
  scaler:
    n_quantiles: 0

model:
  G:
    noise_dim: 256
    fc_dim: 256
    num_layers: 5
    normalization: 'bn' # ln, gn, in, bn
    use_spectral: True
  C:
    fc_dim: 256
    num_layers: 5
    normalization: 'in' # ln, gn, in, bn
    use_spectral: True

losses:
  adv_type: 'wgan' # wgan, lsgan, cramergan, jsgan
  use_gp: True
  G:
    adversarial: 1
  C:
    adversarial: 1
    gradient_penalty: 10

experiment:
  particle: '' # specify for each run
  data:
    context_dim: 3
    data_dim: 5
  weights:
    n_quantiles: -1
    positive: False
    enable: True
  checkpoint_path: '.'
  grad_clip: 10
  epochs: 1000
  batch_size: 2048
  lr:
    G: 0.001
    C: 0.005

metric:
  max_elements: 1000000
  ks:
    bins: 20
  efficiency:
    make_ratio: True
    bins: 10
    thresholds: [0.05,0.10,0.25,0.50,0.75,0.90,0.95]
  classification:
    split_size: 0.5
    iterations: 500
    verbose_each_iter: 1000 # 0 for no output
    depth: 5



utils:
  device: "cuda:0"
  num_workers: 0
  save_interval: 5
  eval_interval: 5
  log_iter_interval: 50
  epoch_iters: 1000

wandb:
  project_name: rich-2021
  enabled: True
  api_key: ''

